[package]
name = "jetson-cool"
version = "0.1.0"
authors = ["Adrian Stanciu <stanciu.adrian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itoa = "0.4"
